[build_machinery] fix CXL link error by making CXL_ACPI a module
Summary:
Commit af9bf9889663 ("cxl: Move devm_cxl_add_nvdimm_bridge() to
cxl_pmem.ko"), backported to v6.18.17-fbk0 as a stable dependency of
96a1fd0d84b1 ("cxl: Fix race of nvdimm_bus object when creating nvdimm
objects"), split the function into an internal
__devm_cxl_add_nvdimm_bridge() restricted to cxl_pmem via
EXPORT_SYMBOL_FOR_MODULES, and a public wrapper
devm_cxl_add_nvdimm_bridge() in drivers/cxl/pmem.c exported with
EXPORT_SYMBOL_NS_GPL.

The fb config has LIBNVDIMM=m which forces CXL_PMEM=m, so the wrapper
lives in a loadable module. With CXL_ACPI=y (built-in), the linker
cannot resolve devm_cxl_add_nvdimm_bridge from a module at link time:

  ld: vmlinux.o: in function `add_root_nvdimm_bridge':
  drivers/cxl/acpi.c:765: undefined reference to `devm_cxl_add_nvdimm_bridge'

The proper upstream fix is 93d0fcdddc9e ("cxl/acpi: Fix CXL_ACPI and
CXL_PMEM Kconfig tristate mismatch") which adds a Kconfig dependency
to prevent CXL_ACPI from being built-in when CXL_PMEM is a module.
That fix was not backported to v6.18-stable.
We should backport that fix to the affected kernel versions as well
in addition to that change.

Affected versions: v6.18.17-fbk0, v6.18.18-fbk0.

Signed-off-by: Atish Patra <atishp@meta.com>

Test Plan:
facebook/scripts/prepareconfig -a x86_64 -f cvmguest -p facebook/config > build/cvmguest/.config
make O=build/cvmguest olddefconfig
make O=build/cvmguest -j$(nproc) bzImage

facebook/scripts/prepareconfig -a x86_64 -f cvmhost -p facebook/config > build/cvmhost/.config
make O=build/cvmhost olddefconfig
make O=build/cvmhost -j$(nproc) bzImage

Verify CXL_ACPI=m in both configs:
grep CONFIG_CXL_ACPI build/cvmguest/.config build/cvmhost/.config

Build suceed without any linker error

Reviewers: mkutsevol, aeh, kbusch, youngjaelee, thevlad, uarif, leit

Reviewed By: mkutsevol

Subscribers: ps, tulloch, youngjaelee, jkkm

Differential Revision: https://phabricator.intern.facebook.com/D100430080

Tasks: T136749058